### ISSUE TITLE
restricted relaying is case sensitive

### ISSUE THREAD

**Issue by ghost** [elokapina/middleman#21]
My bot's mxid is @cog:myserver.tld, with a displayed nick of `Cog`. however, mentions of Cog in rooms do not trigger middlemanbot to relay the message to the control room, only messages where the person specifically says `cog` (lowercase, which matches the localpart of the mxid). there should at least be an option to make this case-insensitive.

**Comment by williamkray** [comment]
oof, i opend that issue with my work github account. well whatever.

**Comment by jaywink** [comment]
Should be fixed, please reopen if not!
